import configparser

config= configparser.ConfigParser()

config.read('config.ini')

AZURE_OPENAI_API_KEY= config['OPENAI']['AZURE_OPENAI_API_KEY']
AZURE_OPENAI_ENDPOINT= config['OPENAI']['AZURE_OPENAI_ENDPOINT']
CONNECTION_STRING= config['CONNECTION_STRING']['CONNECTION_STRING']
SECRET_KEY= config['ENCODING']['SECRET_KEY']
ALGORITHM= config['ENCODING']['ALGORITHM']
AZURE_CONNECTION_STRING= config['STORAGE']['AZURE_CONNECTION_STRING']
AZURE_STORAGE_URL = config['STORAGE']['AZURE_STORAGE_URL']


